export const paises = [ 
    "Albania",
    "Andorra",
    "Armenia",
    "Austria",
    "Azerbaiyan", 
    "Bielorrusia",
    "Belgica", 
    "Bosnia y Herzegovina",
    "Bulgaria",
    "Croacia",
    "Chipre",
    "Republica Checa", 
    "Dinamarca",
    "Estonia",
    "Finlandia",
    "Francia",
    "Georgia",
    "Alemania",
    "Grecia",
    "Hungri­a", 
    "Islandia",
    "Irlanda",
    "Italia",
    "Kazajistan", 
    "Kosovo",
    "Latvia",
    "Liechtenstein",
    "Lituania",
    "Luxemburgo",
    "Macedonia",
    "Malta",
    "Moldavia",
    "Monaco", 
    "Montenegro",
    "Pai­ses Bajos", 
    "Noruega",
    "Polonia",
    "Portugal",
    "Rumania",
    "Rusia",
    "San Marino",
    "Serbia",
    "Eslovaquia",
    "Eslovenia",
    "España", 
    "Suecia",
    "Suiza",
    "Turquia", 
    "Ucrania",
    "Reino Unido"
];